import HeroSection from "../components/HeroSection";

export default function App() {
    return (
        <>
            <HeroSection />
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
            <p>p</p>
        </>
    )
}
